name: chart-servicebus pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    name: hmcts/cnp-azuredevops-libraries
    ref: refs/heads/dtspo-34311-upgrade-helm-validation-pl-v4
    endpoint: 'hmcts'

parameters:
- name: validationJobs
  type: object
  default:
    - jobName: Validate
      chartReleaseName: chart-servicebus-ci
      valuesFile: ci-values.yaml
      kubeconformValuesFile: ci-values-minimal.yaml
      runUnitTests: true
      helmUnittestValuesFiles:
        - "ci-values.yaml"

pool:
  vmImage: 'ubuntu-latest'

jobs:
- ${{ each validateJob in parameters.validationJobs }}:
  - job: ${{ validateJob.jobName }}
    steps:
    - template: steps/charts/validate.yaml@cnp-azuredevops-libraries
      parameters:
        chartName: servicebus
        chartReleaseName: ${{ validateJob.chartReleaseName }}
        chartNamespace: chart-tests
        helmDeleteWait: "120"
        helmInstallWait: "120"
        valuesFile: ${{ validateJob.valuesFile }}
        kubeconformValuesFile: ${{ validateJob.kubeconformValuesFile }}
        generateAsoSchemas: true
        asoVersion: v2.17.0
        runUnitTests: ${{ validateJob.runUnitTests }}
        helmUnittestValuesFiles: ${{ validateJob.helmUnittestValuesFiles }}

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn:
  - Validate
  steps:
  - template: steps/charts/release.yaml@cnp-azuredevops-libraries
    parameters:
      chartName: servicebus
      chartReleaseName: chart-servicebus
      chartNamespace: chart-tests
