---
#
# Service Catalog Servicebus namespace
# https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/servicebus.md
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: servicebus-namespace-{{ .Release.Name }}
  labels: 
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterServiceClassExternalName: azure-servicebus-namespace
  clusterServicePlanExternalName: {{ .Values.serviceplan }}
  parameters:
#    this does not seem to work at the moment.
#    tags:
#      app.kubernetes.io/name: {{ .Release.Name }}
#      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    location: {{ .Values.location }}
    alias: servicebus-namespace-alias-{{ .Release.Name }}
    resourceGroup: {{ required "A resource group ( .Values.servicebus.resourceGroup ) is required service bus creation" .Values.resourceGroup | quote }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: servicebus-namespace-binding-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name  }}
spec:
  instanceRef:
    name: servicebus-namespace-{{ .Release.Name }}
  # map across the connectionString
  secretName: servicebus-secret-namespace-{{ .Release.Name }}


{{- if .Values.setup -}}
  {{- if .Values.setup.queues -}}
    {{- $releaseName:=.Release.Name -}} 
    {{- range $queue := .Values.setup.queues -}}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: servicebus-queue-{{ $releaseName }-{{ $queue.name }}
  labels: 
    app.kubernetes.io/name: {{ $releaseName }}
spec:
  clusterServiceClassExternalName: azure-servicebus-queue
  clusterServicePlanExternalName: queue
  parameters:
    parentAlias: {{ $releaseName }}-alias
    queueName: {{ $queue.name }}
    maxQueueSize: {{ default $queue.maxQueueSize  1024 }}	
    messageTimeToLive: {{ default $queue.messageTimeToLive "PT336H" }}
    lockDuration: {{ default $queue.lockDuration "PT30S"}}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: servicebus-queue-binding-{{ $releaseName }}-{{ $queue.name }}
  labels:
    app.kubernetes.io/name: {{ $releaseName  }}
    app.kubernetes.io/instance: {{ $releaseName  }}
spec:
  instanceRef:
    name: servicebus-queue-{{ $releaseName }}-{{ $queue.name }}
  # map across the connectionString
  secretName: servicebus-secret-queue-{{ $releaseName }}-{{ $queue.name }}
    {{- end -}}
  {{- end -}}
{{- end -}}