---
#
# Service Catalog Servicebus namespace
# https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/servicebus.md
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: servicebus-namespace-{{ template "hmcts.servicebus.releaseName" . }}
  labels:
    {{- ( include "hmcts.servicebus.labels" . ) | indent 4 }}
spec:
  clusterServiceClassExternalName: azure-servicebus-namespace
  clusterServicePlanExternalName: {{ .Values.serviceplan }}
  parameters:
    location: {{ .Values.location }}
    alias: servicebus-namespace-alias-{{ template "hmcts.servicebus.releaseName" . }}
    resourceGroup: {{ required "A resource group ( .Values.servicebus.resourceGroup ) is required service bus creation" .Values.resourceGroup | quote }}
    tags:
      app.kubernetes.io_name: {{ template "hmcts.servicebus.releaseName" . }}
      helm.sh_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      "Team Name": {{ required "A team name (.Values.teamName) is required" .Values.teamName }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: servicebus-namespace-binding-{{ template "hmcts.servicebus.releaseName" . }}
  labels:
    {{- ( include "hmcts.servicebus.labels" . ) | indent 4 }}
spec:
  instanceRef:
    name: servicebus-namespace-{{ template "hmcts.servicebus.releaseName" . }}
  # map across the connectionString
  secretName: servicebus-secret-namespace-{{ template "hmcts.servicebus.releaseName" . }}

{{- if .Values.setup -}}
  {{- if .Values.setup.queues -}}
    {{- $base := . -}}
    {{- range $queue := .Values.setup.queues }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: servicebus-queue-{{ template "hmcts.servicebus.releaseName" $base }}-{{ required "All .Values.servicebus.setup.queues items need a 'name' property" $queue.name }}
  labels:
    {{- ( include "hmcts.servicebus.labels" $base ) | indent 4 }}
spec:
  clusterServiceClassExternalName: azure-servicebus-queue
  clusterServicePlanExternalName: queue
  parameters:
    parentAlias: servicebus-namespace-alias-{{ template "hmcts.servicebus.releaseName" $base }}
    queueName: {{ $queue.name }}
    maxQueueSize: {{ default $queue.maxQueueSize  1024 }}
    messageTimeToLive: {{ default $queue.messageTimeToLive "PT336H" }}
    lockDuration: {{ default $queue.lockDuration "PT30S"}}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: servicebus-queue-binding-{{ template "hmcts.servicebus.releaseName" $base }}-{{ $queue.name }}
  labels:
    {{- (include "hmcts.servicebus.labels" $base) | indent 4 }}
spec:
  instanceRef:
    name: servicebus-queue-{{ template "hmcts.servicebus.releaseName" $base }}-{{ $queue.name }}
  # map across the connectionString
  secretName: servicebus-secret-queue-{{ template "hmcts.servicebus.releaseName" $base }}-{{ $queue.name }}
    {{- end -}}
  {{- end -}}
{{- end -}}
