---
#
# Service Catalog Servicebus namespace
# https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/servicebus.md
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: servicebus-namespace-{{ template "hmcts.releasename.v2" . }}
  {{- ( include "hmcts.labels.v2" . ) | indent 2 }}
spec:
  clusterServiceClassExternalName: azure-servicebus-namespace
  clusterServicePlanExternalName: {{ .Values.serviceplan }}
  parameters:
    location: {{ .Values.location }}
    alias: servicebus-namespace-alias-{{ template "hmcts.releasename.v2" . }}
    resourceGroup: {{ required "A resource group ( .Values.servicebus.resourceGroup ) is required service bus creation" .Values.resourceGroup | quote }}
    tags:
      app.kubernetes.io_name: {{ template "hmcts.releasename.v2" . }}
      helm.sh_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      "Team Name": {{ required "A team name (.Values.teamName) is required" .Values.teamName }}
      "application": {{ required "An application tag name (.Values.applicationName) is required" .Values.applicationName }}
      "builtFrom": {{ required "Repo built from (.Values.builtFrom) is required" .Values.builtFrom }}
      "businessArea": {{ required "Business Area name (.Values.businessArea) is required" .Values.businessArea }}
      "environment": {{ required "Environment name (.Values.environment) is required" .Values.environment }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: servicebus-namespace-binding-{{ template "hmcts.releasename.v2" . }}
  {{- ( include "hmcts.labels.v2" . ) | indent 2 }}
spec:
  instanceRef:
    name: servicebus-namespace-{{ template "hmcts.releasename.v2" . }}
  # map across the connectionString
  secretName: servicebus-secret-namespace-{{ template "hmcts.releasename.v2" . }}

{{- if .Values.setup -}}

  {{- if .Values.setup.queues -}}
    {{- $base := . -}}
    {{- range $queue := .Values.setup.queues }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: servicebus-queue-{{ template "hmcts.releasename.v2" $base }}-{{ required "All .Values.servicebus.setup.queues items need a 'name' property" $queue.name }}
  {{- ( include "hmcts.labels.v2" $base ) | indent 2 }}
spec:
  clusterServiceClassExternalName: azure-servicebus-queue
  clusterServicePlanExternalName: queue
  parameters:
    parentAlias: servicebus-namespace-alias-{{ template "hmcts.releasename.v2" $base }}
    queueName: {{ $queue.name }}
    maxQueueSize: {{ default $queue.maxQueueSize  1024 }}
    messageTimeToLive: {{ default $queue.messageTimeToLive "PT336H" }}
    lockDuration: {{ default $queue.lockDuration "PT30S"}}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: servicebus-queue-binding-{{ template "hmcts.releasename.v2" $base }}-{{ $queue.name }}
  {{- (include "hmcts.labels.v2" $base) | indent 2 }}
spec:
  instanceRef:
    name: servicebus-queue-{{ template "hmcts.releasename.v2" $base }}-{{ $queue.name }}
  # map across the connectionString
  secretName: servicebus-secret-queue-{{ template "hmcts.releasename.v2" $base }}-{{ $queue.name }}
    {{- end -}}
  {{- end -}}

  {{- if .Values.setup.topics -}}
  {{- $base := . -}}
  {{- range $topic := .Values.setup.topics }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: servicebus-topic-{{ template "hmcts.releasename.v2" $base }}-{{ required "All .Values.servicebus.setup.topics items need a 'name' property" $topic.name }}
  {{- ( include "hmcts.labels.v2" $base ) | indent 2 }}
spec:
  clusterServiceClassExternalName: azure-servicebus-topic
  clusterServicePlanExternalName: topic
  parameters:
    parentAlias: servicebus-namespace-alias-{{ template "hmcts.releasename.v2" $base }}
    topicName: {{ $topic.name }}
    maxTopicSize: {{ default $topic.maxTopicSize  1024 }}
    messageTimeToLive: {{ default $topic.messageTimeToLive "PT336H" }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: servicebus-topic-binding-{{ template "hmcts.releasename.v2" $base }}-{{ $topic.name }}
  {{- (include "hmcts.labels.v2" $base) | indent 2 }}
spec:
  instanceRef:
    name: servicebus-topic-{{ template "hmcts.releasename.v2" $base }}-{{ $topic.name }}
  # map across the connectionString
  secretName: servicebus-secret-topic-{{ template "hmcts.releasename.v2" $base }}-{{ $topic.name }}
  parameters:
    subscriptionNeeded: "{{ if $topic.subscriptionNeeded }}yes{{ else }}no{{ end}}"
    {{- end -}}
  {{- end -}}

{{- end -}}

