{{- $root := .Values | default dict -}}
{{- $globals := .Values.global | default dict -}}
{{- $tags := $globals.tags | default dict -}}
{{- $base := . -}}
{{- if .Values.setup -}}
  {{- if .Values.setup.queues -}}
    {{- range $queue := .Values.setup.queues }}
---
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: NamespacesQueue
metadata:
  name: queue-{{ template "hmcts.servicebus.releaseName" $base }}-{{ $queue.name }}
  {{- ( include "hmcts.labels.v2" $base ) | indent 2 }}
spec:
  owner:
    name: {{ $root.namespace }}
  azureName: {{ $queue.name }}
    {{- end }}
  {{- end }}

  {{- if .Values.setup.topics -}}
    {{- range $topics := .Values.setup.topics }}
---
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: NamespacesTopic
metadata:
  name: topic-{{ template "hmcts.servicebus.releaseName" $base }}-{{ $topics.name }}
  {{- ( include "hmcts.labels.v2" $base ) | indent 2 }}
spec:
  owner:
    name: {{ $root.namespace }}
  azureName: {{ $topics.name }}
      {{- if $topics.subscriptionNeeded -}}
---
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: NamespacesTopicsSubscription
metadata:
  name: topic-subscription-{{ template "hmcts.servicebus.releaseName" $base }}-{{ $topics.name }}
  {{- ( include "hmcts.labels.v2" $base ) | indent 2 }}
spec:
  owner:
    name: topic-{{ template "hmcts.servicebus.releaseName" $base }}-{{ $topics.name }}
  azureName: {{ $topics.name }}
  requiresSession: true
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
