{{- $globals := .Values.global | default dict -}}
{{- $tags := $globals.tags | default dict -}}
---
#
# ASO Servicebus examples
# https://github.com/Azure/azure-service-operator/tree/main/v2/samples/servicebus
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: Namespace
metadata:
  name: sb-ns-{{ template "hmcts.releasename.v2" . }}
  {{- ( include "hmcts.labels.v2" . ) | indent 2 }}
spec:
  location: {{ .Values.location }}
  owner:
    name: {{ required "A resource group ( .Values.servicebus.resourceGroup ) is required" .Values.resourceGroup | quote }}
  sku:
    name: Standard
  tags: 
      app.kubernetes.io_name: {{ template "hmcts.releasename.v2" . }}
      helm.sh_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      "Team Name": {{ required "A team name (.Values.tags.teamName) is required" (.Values.tags.teamName | default $tags.teamName) }}
      "application": {{ required "An application tag name (.Values.tags.applicationName) is required"  (.Values.tags.applicationName | default $tags.applicationName) }}
      "builtFrom": {{ required "Repo built from (.Values.tags.builtFrom) is required" (.Values.tags.builtFrom | default $tags.builtFrom) }}
      "businessArea": {{ required "Business Area name (.Values.tags.businessArea) is required" (.Values.tags.businessArea | default $tags.businessArea) }}
      "environment": {{ required "Environment name (.Values.tags.environment) is required" (.Values.tags.environment | default $tags.environment) }}
  zoneRedundant: false
---
apiVersion: managedidentity.azure.com/v1beta20181130
kind: UserAssignedIdentity
metadata:
  name: sb-{{ template "hmcts.releasename.v2" . }}-mi
  {{- ( include "hmcts.labels.v2" . ) | indent 2 }}
spec:
  location: {{ .Values.location }}
  owner:
    name: {{ required "A resource group ( .Values.servicebus.resourceGroup ) is required" .Values.resourceGroup | quote }}
  operatorSpec:
    configMaps:
      # Export the principalId, clientId and tenantId to a ConfigMap
      principalId:
        name: identity-settings
        key: principalId
      clientId:
        name: identity-settings
        key: clientId
      # tenantId:
      #   name: identity-settings
      #   key: tenantId
---
apiVersion: authorization.azure.com/v1beta20200801preview
kind: RoleAssignment
metadata:
  name: {{ uuidv4 }} # Should be UUID
  {{- ( include "hmcts.labels.v2" . ) | indent 2 }}
spec:
  location: {{ .Values.location }}
  # This resource can be owned by any resource.
  owner:
    name: {{ required "A resource group ( .Values.servicebus.resourceGroup ) is required" .Values.resourceGroup | quote }}
    group: resources.azure.com
    kind: ResourceGroup
  # Principal ID of the AAD identity to which the role will be assigned
  principalIdFromConfig:
    name: identity-settings
    key: principalId
  roleDefinitionReference:
    # This ARM ID represents "Contributor" - you can read about other built in roles here: https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles
    armId: /subscriptions/{{ .Values.subscriptionId }}/providers/Microsoft.Authorization/roleDefinitions/090c5cfd-751d-490a-894a-3ce6f1109419

{{- if .Values.setup -}}

  {{- if .Values.setup.queues -}}
    {{- $base := . -}}
    {{- range $queue := .Values.setup.queues }}
---
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: NamespacesQueue
metadata:
  name: {{ required "All .Values.servicebus.setup.queues items need a 'name' property" $queue.name }}
  {{- ( include "hmcts.labels.v2" $base ) | indent 2 }}
spec:
  azureName: {{ $queue.name }}
  defaultMessageTimeToLive: {{ default $queue.messageTimeToLive "PT336H" }}
  lockDuration: {{ default $queue.lockDuration "PT30S"}}
  maxSizeInMegabytes: {{ default $queue.maxQueueSize  1024 }}
  owner:
    name: sb-ns-{{ template "hmcts.releasename.v2" $base }}
    {{- end -}}
  {{- end -}}

  {{- if .Values.setup.topics -}}
    {{- $base := . -}}
    {{- range $topic := .Values.setup.topics }}
---
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: NamespacesTopic
metadata:
  name: {{ required "All .Values.servicebus.setup.topics items need a 'name' property" $topic.name }}
  {{- ( include "hmcts.labels.v2" $base ) | indent 2 }}
spec:
  azureName: {{ $topic.name }}
  defaultMessageTimeToLive: {{ default $topic.messageTimeToLive "PT336H" }}
  maxSizeInMegabytes: {{ default $topic.maxTopicSize  1024 }}
  owner:
    name: sb-ns-{{ template "hmcts.releasename.v2" $base }}
      {{- if $topic.subscriptionNeeded }}
---
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: NamespacesTopicsSubscription
metadata:
  name: sb-sub-{{ required "All .Values.servicebus.setup.topics items need a 'name' property" $topic.name }}
spec:
  owner:
    name: {{ required "All .Values.servicebus.setup.topics items need a 'name' property" $topic.name }}
        {{- end -}}
      {{- end -}}
  {{- end -}}
{{- end -}}

