{{- $base := . -}}
{{- $namespace := .Values.sbNamespace -}}
{{- if .Values.setup.topics -}}
  {{- range $topics := .Values.setup.topics }}
---
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: NamespacesTopic
metadata:
  name: {{ template "hmcts.releasename.v2" $base }}-{{ $topics.name }}
  {{- ( include "hmcts.labels.v2" $base ) | indent 2 }}
spec:
  owner:
    name: {{ required "A Service Bus Namespace ( $namespace ) is required" $namespace }}
  azureName: {{ template "hmcts.releasename.v2" $base }}-{{ $topics.name }}
  {{- if $topics.subscriptionNeeded }}
---
apiVersion: servicebus.azure.com/v1beta20210101preview
kind: NamespacesTopicsSubscription
metadata:
  name: {{ template "hmcts.releasename.v2" $base }}-{{ $topics.name }}
  {{- ( include "hmcts.labels.v2" $base ) | indent 2 }}
spec:
  owner:
    name: {{ template "hmcts.releasename.v2" $base }}-{{ $topics.name }}
  azureName: {{ template "hmcts.releasename.v2" $base }}-{{ $topics.name }}
  requiresSession: {{ $topics.requiresSession | default false }}
    {{- end }}
  {{- end }}
{{- end }}
